Marketplace_app/myproject/communication/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

Marketplace_app/myproject/core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .forms import SignInForm
app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('signin/', auth_views.LoginView.as_view(template_name='signin.html', authentication_form=SignInForm), name='signin'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Marketplace_app/myproject/dashboard/urls.py
from django.urls import path
from . import views
app_name = 'dashboard'
urlpatterns = [
    path('dashboard/', views.index, name='index'),
]

Marketplace_app/myproject/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('item/<int:pk>/', views.detail, name='detail'),
    path('item/new/', views.create, name='create'),
    path('item/<int:pk>/delete/', views.delete, name='delete'),
    path('item/<int:pk>/edit/', views.edit, name='edit'),
    path('', views.items, name='items'),
]

Marketplace_app/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('item/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('communication/', include('communication.urls')),
    path('logout/', auth_views.LogoutView.as_view(next_page='core:signin'), name='logout'),
]

Marketplace_app/myproject/dashboard/models.py
from django.db import models

# Create your models here.

Marketplace_app/myproject/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class SignInForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'w-full p-2 border border-gray-300 rounded', 'placeholder': ' Your Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'w-full p-2 border border-gray-300 rounded', 'placeholder': ' Your Password'}))

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Required. Enter a valid email address.')

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'w-full p-2 border border-gray-300 rounded', 'placeholder': ' Your Username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'w-full p-2 border border-gray-300 rounded', 'placeholder': ' Your Email Address'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'w-full p-2 border border-gray-300 rounded', 'placeholder': ' Your Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'w-full p-2 border border-gray-300 rounded', 'placeholder': ' Confirm Password'}))

Marketplace_app/myproject/dashboard/views.py
from django.shortcuts import get_object_or_404, render
from item.models import Item, Category
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def index(request):
    items = Item.objects.filter(created_by=request.user).order_by('-created_at')
    categories = Category.objects.all()
    return render(request, '.dashboard.html', {'items': items, 'categories': categories})

Marketplace_app/myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{% endblock %}
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
<nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
  <a href="/" class="text-xl font-semibold">Bimbo</a>

  <div class="flex space-x-6 items-center">
    <a href="{% url 'item:create' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
    <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
    
    {% if user.is_authenticated %}
      <a href="{% url 'conversation:inbox' %}" class="text-lg font-semibold hover:text-gray-500">Inbox</a>
      <a href="{% url 'core:contact' %}" class="text-lg font-semibold hover:text-gray-500">Contact</a>

      <form method="POST" action="{% url 'logout' %}" class="inline">
        {% csrf_token %}
        <button type="submit" class="px-6 py-3 text-lg font-semibold bg-red-500 hover:bg-red-700 text-white rounded-xl">
          Logout
        </button>
      </form>
    {% else %}
      <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
      <a href="{% url 'core:signin' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
    {% endif %}
  </div>
</nav>

    <div class="px-6 py-6">
    {% block content %}
    {% endblock %}
    </div>
    <footer class="py-6 px-6 flex justify-between bg-gray-800 ">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About Bimbo</h3>
            <p class="text-lg text-gray-500">Bimbo is a Market place platform that connects people from all over the world.</p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-3 text-lg">
                <li><a href="/" class="hover:text-gray-300">Home</a></li>
                <li><a href="{% url 'core:contact' %}" class="hover:text-gray-300">Contact</a></li>
                <li><a href="{% url 'item:items' %}" class="hover:text-gray-300">Browse</a></li>
                <li><a href="{% url 'core:signup' %}" class="hover:text-gray-300">Sign Up</a></li>
                <li><a href="{% url 'core:signin' %}" class="hover:text-gray-300">Login</a></li>
            </ul>
        </div>
    </footer>
    <footer class="px-6 py-4 flex justify-center bg-gray-800">
  <p class="text-center text-white">&copy; 2024 Bimbo, Inc. All rights reserved.</p>
</footer>

</body>
</html>

Marketplace_app/myproject/templates/contact.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
    <h2>This is the Contact Page</h2>
    <p>Welcome to the contact page of the website. (in development)</p>
{% endblock %}

Marketplace_app/myproject/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-2xl font-bold mb-4">Dashboard</h1>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center"><strong>Your Items</strong></h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            {% for item in items %}
                <div class="bg-white p-4 rounded-lg shadow hover:shadow-lg transition-shadow duration-300">
                    <a href="{% url 'item:detail' item.pk %}">
                        <div>{% if item.image %}<img src="{{ item.image.url }}" alt="{{ item.name }}" class="w-full h-48 object-cover rounded-md mb-4">{% else %}<div class="w-full h-48 bg-gray-200 rounded-md mb-4"><img src="{{ item_images.default.png }}" alt="Placeholder" class="w-full h-48 object-cover rounded-md mb-4"></div>{% endif %}</div>
                        <h3 class="text-lg font-semibold mb-2">{{ item.name }}</h3>
                        <p class="text-gray-600 mb-1">{{ item.description|truncatewords:15 }}</p>
                        <p class="text-blue-600 font-bold">${{ item.price }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            {% for category in categories %}
                <div class="bg-white p-4 rounded-lg shadow hover:shadow-lg transition-shadow duration-300">
                    <a href="#">
                        <div></div>
                        <h3 class="text-lg font-semibold mb-2">{{ category.name }}</h3>
                        <p class="text-gray-600 mb-1">{{ category.items.count }} items</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

Marketplace_app/myproject/templates/index.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            {% for item in items %}
                <div class="bg-white p-4 rounded-lg shadow hover:shadow-lg transition-shadow duration-300">
                    <a href="{% url 'item:detail' item.pk %}">
                        <div>{% if item.image %}<img src="{{ item.image.url }}" alt="{{ item.name }}" class="w-full h-48 object-cover rounded-md mb-4">{% else %}<div class="w-full h-48 bg-gray-200 rounded-md mb-4"><img src="{{ item_images.default.png }}" alt="Placeholder" class="w-full h-48 object-cover rounded-md mb-4"></div>{% endif %}</div>
                        <h3 class="text-lg font-semibold mb-2">{{ item.name }}</h3>
                        <p class="text-gray-600 mb-1">{{ item.description|truncatewords:15 }}</p>
                        <p class="text-blue-600 font-bold">${{ item.price }}</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            {% for category in categories %}
                <div class="bg-white p-4 rounded-lg shadow hover:shadow-lg transition-shadow duration-300">
                    <a href="{% url 'item:items' %}?category={{ category.id }}">
                        <div></div>
                        <h3 class="text-lg font-semibold mb-2">{{ category.name }}</h3>
                        <p class="text-gray-600 mb-1">{{ category.items.count }} items</p>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

Marketplace_app/myproject/templates/signin.html
{% extends 'base.html' %}
{% block content %}
{% block title %}{% endblock %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded shadow">
  <h2 class="text-2xl font-bold mb-4">Log In</h2>
  <form method="post" action="./" class="space-y-4 ">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div>
      <label for="id_username" class="block mb-1 font-semibold">Username</label>
      <p class="text-gray-500" style="font-family: 'Dancing Script', cursive;">
        {{ form.username.errors }}
      </p>
      {{ form.username }}
    </div>
    <div>
      <label for="id_password" class="block mb-1 font-semibold">Password</label>
      <p class="text-gray-500" style="font-family: 'Dancing Script', cursive;">
        {{ form.password.errors }}
      </p>
      {{ form.password }}
    </div>
    <button type="submit" class="w-full py-2 px-4 bg-blue-500 text-white rounded">Sign In</button>
  </form>
</div>
{% endblock %}

Marketplace_app/myproject/templates/signup.html
{% extends "base.html" %}
{% block content %}
{% block title %}{% endblock %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded shadow">
  <h2 class="text-2xl font-bold mb-4">Sign Up</h2>
  <form method="post" action="./" class="space-y-4 ">
    {% csrf_token %}
    {{ form.non_field_errors}}
    <div>
      <label for="id_username" class="block mb-1 font-semibold">Username</label>
<p class="text-gray-500" style="font-family: 'Dancing Script', cursive;">
  {{ form.username.errors }}
</p>


      {{ form.username }}
    </div>
    <div>
      <label for="id_email" class="block mb-1 font-semibold">Email</label>
      <p class="text-gray-500 italic" style="font-family: 'Dancing Script', cursive;">
  {{ form.email.errors }}
</p>
      {{ form.email }}
    </div>
    <div>
      <label for="id_password1" class="block mb-1 font-semibold">Password</label>
      <p class="text-gray-500 italic">
  {{ form.password1.errors }}
</p>
      {{ form.password1 }}
    </div>
    <div>
      <label for="id_password2" class="block mb-1 font-semibold">Confirm Password</label>
      <p class="text-gray-500 italic">
  {{ form.password2.errors }}
</p>
      {{ form.password2 }}
    </div>
    <button type="submit" class="w-full py-2 px-4 bg-blue-500 text-white rounded">Sign Up</button>
  </form>
</div>
{% endblock %}